<?php
$allRoles = (new Acl_Model_Role())
    ->findAll();

$rootRole = null;
$parentRolesList = [];
foreach ($allRoles as $role) {
    if ($role->getParentId()) {
        if (!isset($parentRolesList[$role->getParentId()])) {
            $parentRolesList[$role->getParentId()] = [];
        }
        $parentRolesList[$role->getParentId()][] = $role->getData();
    } else {
        $rootRole = $role->getData();
    }
}

function generateRecursive($content, $parentId, $parentRolesList) {
    if (array_key_exists($parentId, $parentRolesList)) {
        $roles = $parentRolesList[$parentId];
        foreach ($roles as $role) {
            $content .= '
            <li class="role">
                <span>
                    <span class="role-label"><b>' . $role['role_id'] . '&nbsp;-&nbsp;</b>' . $role['label'] . ' (' . $role['code'] . ')</span>
                    <a href="#" 
                       class="pull-right">
                        <i class="folder-delete fa fa-remove" 
                       ng-click="deleteRole(' . $role['role_id'] . ')"></i>
                    </a>
                    <a href="/acl/backoffice_role_edit/role_id/' . $role["role_id"] . '" 
                       class="pull-right">
                        <i class="folder-edit fa fa-pencil"></i>
                    </a>
                </span>';
            $subroles = generateRecursive('', $role['role_id'], $parentRolesList);
            $content .= '
            </li>';

            if (!empty($subroles)) {
                $content .= '
                <ul>' . $subroles . '</ul>';
            }
        }
    }
    return $content;
}

$outputHtml = generateRecursive('', $rootRole['role_id'], $parentRolesList);
?>

<sb-section title="'<?php echo addslashes(__("List of your roles")); ?>'" button="button">
    <br />
    <div class="form-group">
        <label for="filter"><?php echo __("Search"); ?></label>
        <input type="text"
               id="filter"
               class="form-control"
               ng-model="filter"
               placeholder="<?php echo __("Search"); ?>" />
    </div>
    <br />
    <ul class="nested-roles"
        filter-list="filter">
        <li class="role">
            <span>
                <span class="role-label"><b><?php echo $rootRole['role_id']; ?>&nbsp;-&nbsp;</b><?php echo $rootRole['label']; ?> (<?php echo $rootRole['code']; ?> )</span>
                <a href="#"
                   class="pull-right">
                    <i class="folder-delete fa fa-remove"
                       ng-click="deleteRole(<?php echo $rootRole['role_id']; ?>)"></i>
                </a>
                <a href="<?php echo $this->getUrl("acl/backoffice_role_edit", ['role_id' => $rootRole['role_id']]); ?>"
                   class="delete-role pull-right">
                    <i class="folder-edit fa fa-pencil"></i>
                </a>
            </span>
        </li>
        <ul>
            <?php echo $outputHtml; ?>
        </ul>
    </ul>
</sb-section>

<style type="text/css">
    .nested-roles ul {
        padding-left: 30px;
    }

    .delete-role {
        margin-left: 10px;
    }
    .delete-role:hover {
        color: #ff3a2e !important;
    }
</style>