<?php
    $application = $this->getApplication();
?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="advanced_settings_content" class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __("Export / Import"); ?>
                </h3>
                <div id="advanced" class="subcontent content-color">
                    <div class="col-md-12">
                        <?php /**echo $form;*/ ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>